AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  baby-kick-counter-api

  SAM Template for baby-kick-counter-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tags:
      PROJECT: baby-kick-app

Resources:
  KickCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kick-counter/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        Handler:
          Type: Api
          Properties:
            Path: /kick
            Method: post

Outputs:
  KickApi:
    Description: "API Gateway endpoint URL for Prod stage for Kick Counter API function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/kick"
  KickCounterFunction:
    Description: "Kick Counter Lambda Function ARN"
    Value: !GetAtt KickCounterFunction.Arn
  KickCounterFunctionIamRole:
    Description: "Implicit IAM Role created for Kick Counter function"
    Value: !GetAtt KickCounterFunctionRole.Arn
